version: "3.6"

services:
  voting-api:
    image: voting-api
    build:
      context: ./src/voting-api
    environment: 
      REDIS: "redis:6379"
    ports:
      - 8081:80

  voting-ui:
    image: voting-ui
    build:
      context: ./src/voting-ui
    ports:
      - 8080:8080

  voting-api-tests:
    image: voting-api-tests
    build:
      context: ./test/voting-api
    environment: 
      VOTING_API: "http://voting-api/vote"

  redis:
    image: redis
    ports:
      - 6379:6379